import type { Metadata } from "next";
import { ReactNode } from "react";

import Providers from "@/providers";

import "./globals.css";
import "@theme-toggles/react/css/Classic.css";
import "@fontsource-variable/inter";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-ivory text-rich-black dark:bg-rich-black dark:text-ivory">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
